version: '3.8'  # Specify the Compose file format version

services:
  app:
    image: 30882e0acd9b9ab502b6301cc8d11b0828b062a67c57bb3d15d8d7823137b1a5  # Use an image or build from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      # Map host port to container port
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=apica
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=tiger
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: apica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"